# Generated by Django 2.2.6 on 2019-10-18 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cop',
            old_name='location',
            new_name='point',
        ),
    ]
